### ISSUE TITLE
How to bypass login on Quiz attempt?

### ISSUE THREAD

**Issue by harismateen** [Elektryczna-Owca/moodle-python-quiz#1]
How to bypass login on Quiz attempt?

**Comment by tmuras** [comment]
I have pre-created set of users and then logged them in automatically. See https://github.com/Elektryczna-Owca/moodle-python-quiz/commit/cf864893e70433d9f990beb14233682627d22545 

Also have a look at https://tracker.moodle.org/browse/MDL-17892
